### PR TITLE
Pull request for Issue #14

### PR DESCRIPTION
**Pull request by ITblacksheep**
This will dynamically validate against the reports directory and also provide feedback to the user on invalid selections.

### CODE REVIEW

**Comment by ryan-jan** [comment]
Hi,

The `.vscode` folder is part of this repo, it contains formatting settings etc. for the project which we have agreed on 

Could you remove 24c29797 from the pull request and rebase onto the current `dev` branch?

**Comment by ryan-jan** [comment]
Hi again, your recent commit c529eb6 will actually delete the `.gitignore` file entirely, which obviously we don't want. You would need to remove the previous two commits from your branch before we could look at merging this PR. 

Thanks

**Comment by ITblacksheep** [comment]
I'm going to do a rebase and update the pull.

**Comment by ITblacksheep** [comment]
I updated the pull. I did add 2 directories to the .gitignore. One for config/*.json so we don't pull up and commit any config files for customers and one for Output/ where is where I am dropping the output of the scripts. Also may want to include .vscode/launch.json, because when you modify debugging in vscode that gets pull in also.

**Comment by ryan-jan** [comment]
There are now 13 commits in this pull request which is way to many. You need to rebase and squash these into a single commit which clearly explains what you are changing.

Also why have you edited the `vSphere.ps1` in this pull request? And what do your edits on this script provide?

Regarding the `.gitignore` file, I discussed this with Tim and Matt and we decided that it is unnecessary to add these config directories as we can just save these files elsewhere on the file system.

Please can you rework this pull request to just submit your proposed validation improvements to `New-AsBuiltReport.ps1` as a single commit with a clear commit message and summary. Also, ideally commit messages should be in the present tense i.e. Update rather than Updated.

Thanks.

**Comment by ITblacksheep** [comment]
Sorry for the confusion. I was also working on speeding up some stuff in
the vsphere report and forgot to switch branches. I reset my repo last
night and was almost to the point of a pull request when my laptop died. I
will get you one commit today with just the changes to the validation. I
was hoping I could get it straightened out before you saw.

**Pull request closed without merging**
