### PR TITLE
Updated Validation for Type

### PR DESCRIPTION
**Pull request by ITblacksheep**
This commit adds in ValidateScript to get-childitem on the reports directory and validates a correct option was passed.

### CODE REVIEW

**Comment by ITblacksheep** [comment]
@ryan-jan Here is the update with just one commit. I closed out #15.

**Comment by ryan-jan** [comment]
Getting there! However, there are still two commits which you need to squash into one. 

Also please make sure you run the VSCode formatter (highlight your code, right click, Format Selection) on your changes before committing. For example this should reformat your code from:

```
[ValidateScript(
    {
        $ReportTypes = get-childitem "$PSScriptRoot\Reports\" | Select-Object -ExpandProperty Name
        if($ReportTypes -contains $_) {
            return $True
        }
        else {
            throw "Invalid Type specified, $($_). Please use one of the following: $([string]::join(',',$ReportTypes))"
        }
    }
)]
```
To this:
```
[ValidateScript(
    {
        $ReportTypes = get-childitem "$PSScriptRoot\Reports\" | Select-Object -ExpandProperty Name
        if ($ReportTypes -contains $_) {
            return $True
        } else {
            throw "Invalid Type specified, $($_). Please use one of the following: $([string]::join(',',$ReportTypes))"
        }
    }
)]
```

Notice the space after the `if` statement and the `else` is ***not*** on a separate line.

Finally the `get-childitem` should be PascalCase as all PowerShell CmdLets should be, for example `Get-ChildItem`.

**Comment by ITblacksheep** [comment]
Rebased/Squashed/Formatted

**Comment by ryan-jan** [comment]
Can the commit message be edited so that it states what the commit does. In the future, if someone is browsing the commit history, `Fixed Formatting and squashed commits` is not going to mean anything to them. 

Something like `Add parameter validation to Type parameter in New-AsBuiltReport.ps1` would make much more sense in the future.

**Comment by ITblacksheep** [comment]
Commit message has been updated.

**Pull request merged**
